version: 2.1

orbs:
  php: circleci/php@1.0

workflows:
  deploy:
    jobs:
      - approval-for-deploy-tested-up-to-bump:
          type: approval
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /^bump-tested-up-to.*/
      - wp-svn/deploy-tested-up-to-bump:
          context: genesis-svn
          requires:
            - approval-for-deploy-tested-up-to-bump
